language:  csharp
mono: none
dotnet: 3.1

env: 
    - PROJECT="AccelerometerRecipe"
    - PROJECT="AppiumRecipe"
    - PROJECT="BarcodeScanner"
    - PROJECT="BasicInteraction"
    - PROJECT="CRUDCleanArch"
    - PROJECT="CameraRecipe"
    - PROJECT="CleanArchRecipe"
    - PROJECT="ComplexNavigation"
    - PROJECT="DependencyInjectionRecipe"
    - PROJECT="GeolocationRecipe"
    - PROJECT="JSONRecipe"
    - PROJECT="LicenseRecipe"
    - PROJECT="MVVMRecipe"
    - PROJECT="MapsRecipe"
    - PROJECT="MinimalCleanArch"
    - PROJECT="MoneyExample"
    - PROJECT="NavigationRecipe"
    - PROJECT="PickerRecipe"
    - PROJECT="PlaceholderPosts"
    - PROJECT="RESTRecipe"
    - PROJECT="StylingRecipe"
    - PROJECT="TableRecipe"
    - PROJECT="UITestsRecipe"
    - PROJECT="UltimateAnswer"

script:
    - cd $PROJECT
    - cd $PROJECT
    - dotnet build
    - cd ..
    - | 
        if [[ -d "$PROJECT.Tests" ]]
        then 
          cd ${PROJECT}.Tests
          dotnet test
          cd ..
        fi
    - cd ..

